### ISSUE TITLE
🐛 Bug Report: New service is still shown in pending changes despite it has been removed

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4024] opened 2022-10-02 11:56 UTC
### What happened?

![image](https://user-images.githubusercontent.com/6080188/193451744-a44f8f1f-9c55-491a-9da3-65a3a590cfe1.png)
As you can see there are pending changes despite build is already in progress.

### What you expected to happen

Empty pending changes list.

### How to reproduce

Create a new project
Create the first service
Click build
Create the second service
Delete the second service
See that the second service is still shown in pending changes

### Amplication version

v1.0.1

**Comment by Jyotiraditya24** [comment] 2022-10-04 06:26
hey, could I work on this issue?

**Comment by abrl91** [comment] 2022-10-24 12:22
duplicate of: https://github.com/amplication/amplication/issues/3545

**Closed by abrl91** 2022-10-24 12:22 UTC
Labels: type: bug
