### ISSUE TITLE
Improvements for the "Connect to a git repository" screen

### ISSUE THREAD

**Issue by PazYanoverr** [amplication/amplication#7878] opened 2024-01-29 14:38 UTC
![Image](https://github.com/amplication/amplication/assets/149934977/ad8d86aa-ac52-48cc-b102-767e20588a53)

Required improvements:
1. GitLab section should be moved to be after Bitbucket so we have two parts- one includes providers that the user can connect to it, and one includes providers that the user should connect Amplication before.
2. There should be more space between the git providers and the demo repo option / toggle

**Comment by harshil162** [comment] 2024-01-29 20:49
I would like to be assigned this issue as long as it is a fix I can do via writing code.

**Comment by PazYanoverr** [comment] 2024-01-29 21:08
@harshil162 - Sure, this is all about writing code :)
I will assign the ticket to you, and feel free to ping me or @mulygottlieb in case of any questions.

**Comment by harshil162** [comment] 2024-01-31 22:12
@PazYanoverr I'm not sure I am able to find the exact file where the problem is happening. Can you tell me which file this pertains to?

**Comment by PazYanoverr** [comment] 2024-02-01 07:19
@harshil162 - You can find this page as part of creating new resource (Service) flow - create-resource.
If you are asking about the code itself- let me know

**Comment by harshil162** [comment] 2024-02-03 05:51
@PazYanoverr Yes, I was referring to where in the codebase this issue is happening. In other words, what file or files?

**Comment by PazYanoverr** [comment] 2024-02-03 20:08
@mulygottlieb - Can you please assist @harshil162 in his question above?

**Comment by harshil162** [comment] 2024-02-05 04:50
@PazYanoverr I have also contacted Muly via Discord as well and he hasn't responded...

**Comment by Meyazhagan** [comment] 2024-02-05 05:51
@harshil162 https://github.com/amplication/amplication/blob/master/packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx 

hope this helps you

**Comment by mulygottlieb** [comment] 2024-02-05 07:11
@harshil162 you can look into:
https://github.com/amplication/amplication/blob/fdb8a0f75b0dddd46002d1eb1935748cec8198ca/packages/amplication-client/src/Resource/git/ServiceWizardConfigurationGitSettings.tsx

https://github.com/amplication/amplication/blob/fdb8a0f75b0dddd46002d1eb1935748cec8198ca/packages/amplication-client/src/Resource/git/GitActions/GitProviderConnectionList.tsx

https://github.com/amplication/amplication/blob/fdb8a0f75b0dddd46002d1eb1935748cec8198ca/packages/amplication-client/src/Resource/create-resource/wizard-pages/CreateGithubSync.tsx

as good starting points.

In general, the expectation from contributors who request tasks is to be able to navigate the codebase to find the relevant parts.

**Comment by mulygottlieb** [comment] 2024-05-02 08:33
@svihang8 I don't see any progress here, so if you want to be assigned, let me know.

**Comment by svihang8** [comment] 2024-05-02 16:56
Hi @mulygottlieb . I would love to work on this.

**Comment by mulygottlieb** [comment] 2024-05-05 09:18
Assigned to you @svihang8 , good luck!

**Comment by mulygottlieb** [comment] 2024-05-29 08:15
Passed QA:



![Image](https://github.com/amplication/amplication/assets/1912933/d22fd958-c38b-44e0-b846-ce363b71648e)

(the preview repo toggle is no longer available with the new Jovu onboarding)

**Closed by mulygottlieb** 2024-05-29 08:15 UTC
Labels: open to community
