### ISSUE TITLE
🐛 Bug Report:  Upper text is not perfect for small devices

### ISSUE THREAD

**Issue by rohitmondal03** [amplication/amplication#7260] opened 2023-10-15 14:59 UTC
### What happened?

When opening the website in small device, the most upper text is not aligning perfectly with screen. This is happening with every links/routs present.
![Screenshot (104)](https://github.com/amplication/amplication/assets/107113353/62b30d70-c0c3-4ce2-9291-9fd43cd7501d)
![Screenshot (103)](https://github.com/amplication/amplication/assets/107113353/077f1d76-4a96-4f87-b8ed-a667bcf68ae4)

### What you expected to happen

The uppermost texts should be shown perfectly in the screen.

### How to reproduce

1. Head to website [https://amplication.com/](https://amplication.com/)**.
2. Then head to `inspect`, by clicking right mouse button.
3. Then check for the responsiveness of website for small devices.

### Amplication version

v1.10.5

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by abdorah** [comment] 2023-10-16 11:12
Hi!
I checked the same page that you gave in your screenshot. I only changed the css property text-align to center just to see the result.
![image](https://github.com/amplication/amplication/assets/37270435/dd7d4af7-cedf-44d4-b7d3-af93a9d4bd5c)
I wonder is this the kind of issue you are looking to fix?

**Comment by Prashant04627** [comment] 2023-10-18 18:05
Can i work on this issue?

**Comment by lalitkumawat1m** [comment] 2023-10-22 00:55
hey @GreenMachine01, I want to work on this issue please assign to me

**Comment by GreenMachine01** [comment] 2023-10-22 07:53
Closing as duplicate of - https://github.com/amplication/amplication/issues/7287

**Closed by GreenMachine01** 2023-10-22 07:53 UTC
Labels: type: bug
