### ISSUE TITLE
🐛 Bug Report: Wrong dropdown design in our GitHub page

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#2413] opened 2022-03-09 16:49 UTC
### What happened?

Our organization's select button's current design looks different from the original design.

this is how it look now
<img width="1313" alt="image" src="https://user-images.githubusercontent.com/96179897/157488893-1f784677-c715-4fb9-8109-dea1f6767d50.png">

this is how it suppose to look
![a3](https://user-images.githubusercontent.com/96179897/157488991-01532169-a0ed-4283-9051-1ad33ff6020f.png)

Figma file
https://www.figma.com/file/tIfcueoxU4DtYtCHmmLuE7/Community---Task-Assets?node-id=1%3A8353

### What you expected to happen

The select button should include the avatar image.
Currently, it has the same look as our regular button, so it is hard to know that you will get a select organization window when you click on it.

### How to reproduce

Click on the side menu bar on the GitHub icon

### Amplication version

0.11.2

### Environment

.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by jainpawan21** [comment] 2022-03-16 21:04
Hi @alexbass86 and @souravjain540,
I would like to work on this

**Comment by yuval-hazaz** [comment] 2022-03-17 09:23
@jainpawan21 please let us know when you are available to take this task, once you complete the other issue your were assigned to, and we would love to assign this one also

**Comment by jainpawan21** [comment] 2022-03-18 17:43
Hi @yuval-hazaz, I am available to work on this issue.

**Comment by yuval-hazaz** [comment] 2022-03-19 06:55
cool, go ahead

**Comment by jainpawan21** [comment] 2022-03-21 11:48
@yuval-hazaz 

After exploring the root cause of this issue I have found that we need to modify our SelectMenu component in amplication-design-system. We are using @primer/react. As per primer [docs](https://primer.style/react/deprecated/SelectMenu) Select Menu is deprecated.
Shall I rewrite the entire component using the new [Action Menu](https://primer.style/react/ActionMenu) or modify the existing SelectMenu component?

**Comment by yuval-hazaz** [comment] 2022-03-22 11:51
Thanks @jainpawan21. 
Do you know to tell how complicated a migration would be?

If that is something you can handle in a timely manner we can go for it, but let's try to estimate first

**Comment by yuval-hazaz** [comment] 2022-03-29 09:55
@jainpawan21 are you still interested in working on this?

**Comment by jainpawan21** [comment] 2022-03-29 10:37
Yes @yuval-hazaz , Give me some more time. I am working on this issue

**Comment by yuval-hazaz** [comment] 2022-03-29 11:28
perfect, thanks

**Comment by jainpawan21** [comment] 2022-03-30 14:27
Hi @yuval-hazaz , I explored changes in @primer/react package since the 34.1.0 version. There are a few changes which create issue for us.
1. In the 35.1.0 version, they have dropped className props support, now they are supporting [this](https://primer.style/react/overriding-styles) method, but we are using class-based styling.
2. They have changed prop and component types in a few of the components which affect menu as well as other components
3. Button component has now {children} as mandatory props. IconButton is a new component they have added if we want to render just icon as button. But we are using the same Button component as the icon button also.

Although migration will not take much time as I have a fair idea of changes now. I have raised PR with the existing 34.1.0 version. But I think we should address migration in separate PR as It will change a few more components.

**Closed** 2022-04-24 14:58 UTC
Labels: type: bug, good first issue, help wanted, @amplication/client, status: accepted
