### ISSUE TITLE
Server: Access to data by role and according to related company

### ISSUE THREAD

**Issue by pomazanbohdan** [amplication/amplication#875] opened 2020-11-30 08:57 UTC
All my business ideas require levels of access to data not only by role / user, but also access to data that belongs to other users of the related organization.

Currently, there is no such functionality in any product that has such functionality, and significant development on the client side of the application is always necessary.

An example of the database structure of  applications in the attached files.
1. A network of city portals where access is needed
 - Dealer partners
 - company employees
2. Bot providing service by various companies
3. Bot publishing events

[bd.zip](https://github.com/amplication/amplication/files/5614767/bd.zip)

**Comment by iddan** [comment] 2020-11-30 10:04
This is a great idea and possible! We can mimic the code we currently have in the platform for this.

**Comment by yuval-hazaz** [comment] 2020-11-30 10:31
@pomazanbohdan are you referring to a multi-tenant application, where a user belongs to a specific "company" at the highest level, or do you see a need for such a relation at any level of that data ?

**Comment by pomazanbohdan** [comment] 2020-11-30 10:37
> @pomazanbohdan are you referring to a multi-tenant application, where a user belongs to a specific "company" at the highest level, or do you see a need for such a relation at any level of that data ?

Yes

**Comment by pomazanbohdan** [comment] 2020-11-30 10:45
Or even a combination in different implementations

- User 0 Root
-- Site 1
--- User 1 admin
--- User 2 moderator
---- Company 1
----- User 3 as root
----- User 4 as moderator
----- user 5 as client
----- user 8 as client
-- Site 2
--- User 6 admin
--- User 7 moderator
---- Company 2
----- User 5 as root
----- User 6 as moderator
----- user 5 as client
----- user 8 as client

**Comment by iddan** [comment] 2020-12-29 22:58
This feature is also known as Teams, Tenants, or Organizations.

**Comment by yenicelik** [comment] 2021-05-22 23:26
"duplicate" /strong reference with https://github.com/amplication/amplication/issues/1147

**Comment by hmiiro** [comment] 2021-09-11 17:11
It will really be good...actually a super win if, it's possible to have multi-tenant, with configurable options of same dB for all, or seperate dB per tenant for extreme data separation use cases like in financial applications of tenants.  I recall there some library using prima that had this we can benchmark on...here is the repo. https://github.com/Errorname/prisma-multi-tenant

**Comment by yuval-hazaz** [comment] 2022-07-23 08:01
closing this as a duplicate of #1422

**Closed by yuval-hazaz** 2022-07-23 08:01 UTC
Labels: type: feature request
