### ISSUE TITLE
🐛 Bug Report: field level granular permission is missing in delete action

### ISSUE THREAD

**Issue by jainpawan21** [amplication/amplication#3686] opened 2022-09-02 11:42 UTC
### What happened?

See in this 👇🏻 screenshot, all others action has option to customise field level granular permission but delete action is missing
<img width="891" alt="Screenshot 2022-09-02 at 5 02 37 PM" src="https://user-images.githubusercontent.com/39362422/188131891-b45aa737-16e4-435f-bf8c-6bc9bc2a1d42.png">

### What you expected to happen

It should be there in delete action also

### How to reproduce

Go to entities of any project
choose any entity
click on permissions
click on delete action
option to customise field level permission for different roles is missing

### Amplication version

0.15.2

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by arielweinberger** [comment] 2022-09-02 11:49
Hey @jainpawan21 I am not sure if I understand. I see I'm able to attach granular permissions on the Update operation, and I also see this option in your screenshot. Can you elaborate?

**Comment by jainpawan21** [comment] 2022-09-02 12:22
Hi @arielweinberger, by mistake I typed update. This should be delete. I updated everywhere

**Comment by arielweinberger** [comment] 2022-09-02 14:16
This is the intended behavior. Delete refers to deleting an entire resource, not an individual property. I'll close this issue.

**Closed by arielweinberger** 2022-09-02 14:16 UTC
Labels: type: bug
