### ISSUE TITLE
🐛 Bug Report: Delete resource does not clear the pending changes

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3545] opened 2022-08-21 12:49 UTC
### What happened?

Delete resource does not clear the pending changes

### What you expected to happen

When a user deletes a resource immediately after creating, the pending changes should be cleared it

### How to reproduce

- create a resource
- see the pending changes
- delete the resource
- see that the pending changes are still there

### Amplication version

0.15.0

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by GreenMachine01** [comment] 2022-10-25 07:52
Closed duplicate of https://github.com/amplication/amplication/issues/4017

**Closed** 2022-10-25 08:02 UTC
Labels: type: bug, @amplication/client, @amplication/server, status: assigned
