### ISSUE TITLE
🐛 Bug Report: Blank screen on refresh - undefined

### ISSUE THREAD

**Issue by alexbass86** [amplication/amplication#3664] opened 2022-08-31 11:23 UTC
### What happened?

If you are doing a refresh in chrome, we receive a blank screen without any way to return to our main project screen as the logo link redirected us back to the blank screen and not to the main project screen.

Video:
https://user-images.githubusercontent.com/96179897/187667725-64faedcd-f25f-456a-ba99-8c51a9064986.mp4

### What you expected to happen

We should see the commit component when we go into workspace settings/members, and refreshing the screen shouldn't affect the system and will be able to load us the same screen we were in before the refresh.
Also, by clicking on the logo, we should be redirected to the main project screen.

### How to reproduce

Go to the main project screen, and click on the "workspace members/settings." After that, refresh the screen.

### Amplication version

0.15.1

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by barshimi** [comment] 2023-01-22 15:07
this bug was fixed as part of the purchase redirect

**Comment by collinewait** [comment] 2023-05-09 07:53
@alexbass86 you can have a look at this PR https://github.com/amplication/amplication/pull/5916. cc @GreenMachine01. Thanks.

**Comment by GreenMachine01** [comment] 2023-05-09 09:51
@alexbass86 according to Shimi this bug was already fixed. if so we can close this bug.

**Comment by collinewait** [comment] 2023-05-09 10:06
@GreenMachine01 I was able to reproduce it.

**Comment by GreenMachine01** [comment] 2023-05-09 10:13
@collinewait oh. now it's clear. thank you!

**Comment by EugeneTseitlin** [comment] 2023-05-20 22:31
I can't reproduce it right now. 
@GreenMachine01 @barshimi Guys, please, check it also, maybe I'm missing something.

**Comment by GreenMachine01** [comment] 2023-05-30 08:17
@mulygottlieb 
Reproduced so this is still an issue.
I also had the same experience when I was just trying to open the Installed plugins of a service.

**Comment by GreenMachine01** [comment] 2023-07-26 13:29
cant reproduce

**Closed by GreenMachine01** 2023-07-26 13:29 UTC
Labels: type: bug, priority: high, impact: User Experience
