### ISSUE TITLE
Make the qraphQL generated code optional

### ISSUE THREAD

**Issue by nisa10880** [amplication/amplication#2368] opened 2022-03-01 07:54 UTC
Is it possible to make the qraphQL generated code optional? The code will much clearer for those who don't use graphql.

**Comment by yuval-hazaz** [comment] 2022-03-01 08:18
Thanks @nisa10880 
I agree that can be very helpful, and we actually have another issue open with the same request.
We will consider pushing it on the roadmap
Duplicate of #1681

**Closed by yuval-hazaz** 2022-03-01 08:18 UTC
