### ISSUE TITLE
Client: Have a visualisation tool for the entity relations like drawSQL

### ISSUE THREAD

**Issue by gabimoncha** [amplication/amplication#1148] opened 2021-01-18 16:48 UTC
**Is your feature request related to a problem? Please describe.**
I think it would be really nice if we have a visualisation tool for the relations between entities. Something similar with [**drawSQL**](https://drawsql.app). Maybe even create those entities with the help of this visualisation tool.

**Describe the solution you'd like**
The visualisation tool should show the Entities, Fields and the relations between them. You should also have the option to change parameters for the fields.

**Describe alternatives you've considered**
We can draw inspiration from [**drawSQL**](https://drawsql.app)

**Additional context**
Example template
<img width="420" alt="Screenshot 2021-01-18 at 18 48 16" src="https://user-images.githubusercontent.com/39256258/104942961-bd9ff580-59bd-11eb-8b4a-6d21107abbfd.png">

**Comment by yuval-hazaz** [comment] 2022-07-23 14:51
duplicate of https://github.com/amplication/amplication/issues/809

**Closed by yuval-hazaz** 2022-07-23 14:51 UTC
Labels: type: feature request
