### ISSUE TITLE
🐛 Bug Report: constants file in dsg is overwrite

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1901] opened 2021-11-14 06:25 UTC
### 📜 Description

if i use constants file in the it will overwrite in every build

### 👟 Reproduction steps

create app
update server/src/constants
rebuild

### 👍 Expected behavior

using the base/ extend model

### 👎 Actual Behavior

the file is overwrite

### 💻 Device

Desktop

### 💻 Operating system

MacOS

### 🌍 Browser

Firefox

### 👀 Have you spent some time to check if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Code of Conduct](https://github.com/amplication/amplication/blob/master/code_of_conduct.md)

**Comment by mshidlov** [comment] 2022-01-17 18:49
Hi, @tupe12334 Thank you for reporting this issue.
can you please explain which files are overwritten, when, and where?

**Comment by yuval-hazaz** [comment] 2022-01-18 07:14
This is not a bug - this is a feature request and should be handled this way. 
There are many areas in the system where we do not provide a built-in way to customize the code, and it is part of our roadmap to add support for the missing parts. 

I can assume now that it will not be done using the extend/base methods used in other areas, but we will use a different method which we still explore. 

I think we can close this issue as it will be handled as part of the bigger initiative

**Closed** 2022-01-18 12:37 UTC
Labels: type: bug, status: wontfix, @amplication/data-service-generator
