### ISSUE TITLE
🚀Generated App - 1:m relation - enable filtering on the 1 side of the relation

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3067] opened 2022-07-10 14:26 UTC
### Feature description

For now, we generate the {EntityName}ListRelationFilter (every, some, none) only on the "many" side of the relation of 1:m.
It would be helpful to filter also on the "1" side of the relation

### Use case

Sample App for example:
A customer can have many orders (1:m), on the side of the order, we generate this filter DTO, but let's say we want to find every customer that got an x% discount

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by yuval-hazaz** [comment] 2022-07-11 05:26
@abrl91 I am not sure the example with the discount is the best, because usually the discount will be placed on the order (which is 1:m) or on the customer record itself which is not a relation. 

Also, when talking about filtering on the side of the 1 in 1:m, it will not be using every, some, and none - it will be directly on the fields of the relation - 

Using your example - we want to find all the orders, where the customer has an x% discount.

I will add this to the backlog

**Comment by yuval-hazaz** [comment] 2022-07-19 13:18
Closing as duplicate of #1898

**Closed by yuval-hazaz** 2022-07-19 13:18 UTC
Labels: type: feature request, @amplication/data-service-generator
