### ISSUE TITLE
🐛 Bug Report: Request to Update Twitter Icon to X

### ISSUE THREAD

**Issue by lalitkumawat1m** [amplication/amplication#7059] opened 2023-09-08 04:42 UTC
### What happened?

The Twitter logo has been updated recently and hasn't been updated on the site. I didn't find any issue related to this.

URL 
https://amplication.com/

ScreenShot
<img width="916" alt="Screenshot 2023-09-08 100840" src="https://github.com/amplication/amplication/assets/91591901/a6cdda68-e9da-49ac-b666-940fe0c20bc3">

### What you expected to happen

The Twitter logo should be changed to X

### How to reproduce

Scroll to the footer section and see Twitter old logo

@yuval-hazaz 
I am just starting with open source contribution. I would love to take this issue as my first ever contribution could you please assign this to me?

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by AyushDhimanIITR** [comment] 2023-09-30 05:06
Can I work on it?

**Comment by granthpai** [comment] 2023-09-30 05:25
Hi @souravjain540 @GreenMachine01. If the issue is still open, I would like to work on it.

**Comment by lalitkumawat1m** [comment] 2023-09-30 05:27
Hello Team, 
I want to work on this issue please assign it to me

**Comment by Vishrut19** [comment] 2023-10-01 12:06
I want to work on it. Please assign me!

**Comment by astitva0011** [comment] 2023-10-01 17:51
i want to work on this
assign me

**Comment by souravjain540** [comment] 2023-10-02 04:09
@lalitkumawat1m assigned it to you.

**Comment by Kkartik14** [comment] 2023-10-02 17:17
I would like to work on this
Assign it to me

**Comment by Tejodeep2002** [comment] 2023-10-02 18:14
I like to work

**Comment by deauthe** [comment] 2023-10-05 19:33
Can i still work on the issue even though it's assigned?

**Closed** 2023-10-12 05:26 UTC
Labels: good first issue, open to community
