### ISSUE TITLE
Entity Fields Options

### ISSUE THREAD

**Issue by AndrewTraub** [amplication/amplication#1033] opened 2020-12-22 16:58 UTC
When creating an entity of type Options, I cannot enter a number for the value field - only a text string.
Also, it doesn't appear that I can set a default value (but this appears true for other fields as well)

**Comment by yuval-hazaz** [comment] 2020-12-23 09:44
Closing this as a duplicate of #675 

Also, created a new feature request for default fields #1045

**Comment by yuval-hazaz** [comment] 2020-12-23 09:45
Duplicate of #675

**Closed by yuval-hazaz** 2020-12-23 09:44 UTC
Labels: priority: medium, status: confirmed, type: bug

**Comment by yuval-hazaz** [comment] 2020-12-23 09:47
Created #1045
