### ISSUE TITLE
[IMPROVEMENT] change alignment of items in user's profile page

### ISSUE THREAD

**Issue by MAX-786** [amplication/amplication#4269] opened 2022-10-27 12:26 UTC
### What happened?

In the user/profile whole div is aligned left with 0 margin & 0 padding which doesn't look good.
![Screenshot (28)](https://user-images.githubusercontent.com/99530996/198283042-10e3ba0c-4509-4095-8ffa-df35aa2b9aca.png)
the 

### What you expected to happen

If it is aligned center then it may look good like,

![Screenshot (27)](https://user-images.githubusercontent.com/99530996/198283540-6b03719a-a821-411d-bfdf-4256ccf4ecde.png)

### How to reproduce

Just go to the `/user/profile` path and you will encounter it.

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by souravjain540** [comment] 2022-10-28 05:42
@abrl91 please validate

**Comment by abrl91** [comment] 2022-10-28 06:44
sorry, a duplicate of https://github.com/amplication/amplication/issues/3596
and it is already assigned

**Closed** 2022-10-28 06:44 UTC
Labels: type: bug
