### ISSUE TITLE
🐛 Bug Report: EntityOrderByInput dto is not updated with the decorator imports when adding property

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#6394] opened 2023-06-27 14:37 UTC
### What happened?

When adding a JsonValue field, the EntityOrderByInput dto is not updated with the decorator imports   @IsOptional() and
  @IsEnum(SortOrder)

![image](https://github.com/amplication/amplication/assets/54762917/6af6833f-b6da-4fc6-b509-ab5a6648a3e9)

### What you expected to happen

When adding a property to an existing entity, the updated field should also update the added decorators.

In all other auto-generated dtos it is updating correctly all added fields and imports. This happened for me only in the EntityOrderByInput.ts

Current workaround is to simply add imports manually.

This did not happen in previous versions.

### How to reproduce

- Create an Entity and auto-generate code
- Add and json property to the Entity in the Amplication UI
- Create auto-generation pull request
- property is added but the imports are missing

### Amplication version

1.7.6

### Environment

Node: 19.6.0

**Comment by Shurtu-gal** [comment] 2024-01-14 21:20
@vincenzodomina @mulygottlieb I couldn't reproduce this. Steps I followed:

1. Create the bare minimum service with this [PR](https://github.com/ash17290/test-amplication/pull/1).
2. Add JSON field `calulateProperties` to User Entity [here](https://github.com/ash17290/test-amplication/pull/2/commits/c57196dca0f7297cac4dc57769b963bc1b7360f6).
3. Add another test entity with bare minimum `ID` and `createdBy` fields [here](https://github.com/ash17290/test-amplication/pull/2/commits/1b9df6b06d90a763aba9c98b9e7aab99baa2901a).

However, as seen in the following `orderByInput` files the imports for `isOptional` and `isEnum` are already present.

- https://github.com/ash17290/test-amplication/blob/1b9df6b06d90a763aba9c98b9e7aab99baa2901a/apps/sample/src/user/base/UserOrderByInput.ts
- https://github.com/ash17290/test-amplication/blob/1b9df6b06d90a763aba9c98b9e7aab99baa2901a/apps/sample/src/test/base/TestOrderByInput.ts

**Comment by mulygottlieb** [comment] 2024-01-15 07:39
@Shurtu-gal thanks!
I suspect this has already been fixed since the bug was reported in June 2023, and the newer DSG versions have already fixed this. 
I am closing this issue as it is not reproducible anymore.
@vincenzodomina, if you still encounter this, please let us know, and we will re-open the ticket and investigate further.

**Closed by mulygottlieb** 2024-01-15 07:39 UTC
Labels: type: bug, impact: Quality, Sapphire
