### ISSUE TITLE
Enhancement: Make the Profile Page have better styling

### ISSUE THREAD

**Issue by Ahtritus** [amplication/amplication#4224] opened 2022-10-21 18:44 UTC
### Feature description

Currently, the Profile Form in the Profile Page is situated to the extreme left, making it look a bit jarring. A better styling would be preferred.

<img width="338" alt="image" src="https://user-images.githubusercontent.com/53258966/197267362-927d4638-7518-4e55-98bc-9c32c2ae1f40.png">

### Use case

After the required styling changes, the Profile Page should look something like this

<img width="1279" alt="image" src="https://user-images.githubusercontent.com/53258966/197267848-d7333296-8142-4364-b04c-2064f28465bb.png">

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by Ahtritus** [comment] 2022-10-21 19:12
@souravjain540  @yuval-hazaz  Could you please assign this to me and I'll raise the PR?

**Comment by abrl91** [comment] 2022-10-21 20:46
@alexbass86

**Comment by TheLearneer** [comment] 2022-10-22 12:11
@abrl91 I believe this issue is duplicate of #3596

**Comment by Ahtritus** [comment] 2022-10-22 12:14
> @abrl91 @Ahtritus I believe this issue is duplicate of #3596

Whoops, didn't see it there. I guess we can close this issue then?

**Comment by abrl91** [comment] 2022-10-22 15:31
duplicate of https://github.com/amplication/amplication/issues/3596

**Closed by abrl91** 2022-10-22 15:31 UTC
Labels: type: feature request
