### ISSUE TITLE
Cannot select GitHub repo from truncated list

### ISSUE THREAD

**Issue by mikeedwards** [amplication/amplication#1161] opened 2021-01-20 06:20 UTC
**Describe the bug**
After setting up sync with Github, I'm not able to select a repo because the list of existing repos, including _all_ the repos from organizations I'm part of, cuts off after a certain number. The repo I want to use can't be reached.

**To Reproduce**
1. Sync with GitHub
2. Hit the button to select a repo
3. Scroll through the list of available repos. If you have more than a certain number available to you, the list will end and there's not any way to search for or manually enter the desired repo.

**Expected behavior**
Expect to see the desired repo to sync with, either further down the list, on another page of listed repos, or via some kind of search input or manual entry.

**Desktop (please complete the following information):**
 - OS: macOS 10.15.7
 - Browser: Chrome 87

**Comment by yuval-hazaz** [comment] 2021-01-20 09:33
Thanks. I can confirm this is a bug,

**Comment by yuval-hazaz** [comment] 2021-01-21 10:23
@mikeedwards we just pushed a fix that sorts the list by "last updated" of the repo and added a refresh button. As most users will probably link to a newly created repo, it is best anyway to show them first. 
We are also working to add search functionality to permanently resolve the issue. 

Thanks for reporting

**Comment by yuval-hazaz** [comment] 2022-07-23 14:50
duplicate of https://github.com/amplication/amplication/issues/2551

**Closed by yuval-hazaz** 2022-07-23 14:50 UTC
Labels: type: bug, priority: medium, status: confirmed
