### ISSUE TITLE
🐛 Bug Report: UX Minor Bug | the "Unique Field" toggle is off on the automated "ID" Field

### ISSUE THREAD

**Issue by MaorZ** [amplication/amplication#2205] opened 2022-01-19 16:23 UTC
### What happened?

When I look at the Fields section and view the "ID" field I get the following description:
"An automatically created unique identifier of the entity"
But for some reason the "Unique Field" toggle is off:
![image](https://user-images.githubusercontent.com/9624076/150171316-8abb5540-ef8a-477e-983e-08db5f0bb617.png)
![image](https://user-images.githubusercontent.com/9624076/150171344-ed002ce6-d5ab-4b55-9c97-fbced2f0dad2.png)

### What you expected to happen

The "Unique Field" toggle will be "On" like so:
![image](https://user-images.githubusercontent.com/9624076/150171700-417a4456-5a4a-4af6-90d1-8801d8f799b5.png)

### How to reproduce

I was exploring the Sample app to learn about this project and I entered the address entity and into the fields

### Amplication version

0.11.1

### Environment

The test web app:
https://app.amplication.com/

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### Code of Conduct

I agree to follow this project's Code of Conduct

**Comment by yuval-hazaz** [comment] 2022-01-20 06:15
Thanks @MaorZ 
You are correct, the unique toggle should be on and disabled. 
I see that you want to send a PR to fix it, so I will assign the issue to you. Let me know if that is OK. 
If you need any help with a PR the team is available on discord 
https://amplication.com/discord

**Comment by muhsinkamil** [comment] 2022-02-02 14:56
Hi @yuval-hazaz Can I take this up, Since this is my first contribution, I would like to try this.

**Comment by yuval-hazaz** [comment] 2022-02-02 15:19
hi @muhsinkamil 
the issue is now assigned to you

Let us know if you need any help. The team is available on discord to support you if needed 
https://amplication.com/discord

**Closed** 2022-02-04 12:22 UTC
Labels: type: bug, good first issue, @amplication/client, status: assigned
