### ISSUE TITLE
Letting the user know if patch apply has been failed on a section of code

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#5242] opened 2023-02-20 15:53 UTC

**Comment by overbit** [comment] 2023-02-23 09:40
https://github.com/amplication-test/inabit-poc/pull/26/files#diff-7ce369396f9c24293267e1cd57ca29ce33044fde734b2627b81c71e69c467015

**Comment by GreenMachine01** [comment] 2023-02-26 11:09
Duplicate of #5266

**Closed by GreenMachine01** 2023-02-26 11:09 UTC
Labels: epic: GitHub Sync
