### ISSUE TITLE
🐛 Bug Report: Github selection list is incomplete

### ISSUE THREAD

**Issue by darkrift** [amplication/amplication#3406] opened 2022-08-09 14:26 UTC
### What happened?

When I came to try to select a repo to sync the code with, the list is limited to 30 items, which is probably due to paging from GH api. However, it didn't let me load more repositories and select the proper repo to sync with.

### What you expected to happen

Provide a way to load more items, either automatically when reaching the end of the list, or by using paging (next, previous) buttons

### How to reproduce

Have enough personal repo to exceed 30 items in the list and try to select the last in alphabetical order, it won't be visible

**Comment by souravjain540** [comment] 2022-08-09 14:39
Hi @darkrift 👋 

Thanks for reporting this issue :)

We already have this reported here: https://github.com/amplication/amplication/issues/2551

Please see if this is what you reported

**Comment by darkrift** [comment] 2022-08-09 18:30
It is the same, my bad, can close as duplicate

**Comment by souravjain540** [comment] 2022-08-09 18:38
Thanks :) Do you want to contribute?

**Comment by yuval-hazaz** [comment] 2022-08-10 05:57
duplicate of https://github.com/amplication/amplication/issues/2551

**Closed by yuval-hazaz** 2022-08-10 05:57 UTC
Labels: type: bug
