### ISSUE TITLE
🐛 Bug Report: plugin service don't started

### ISSUE THREAD

**Issue by mihailShumilov** [amplication/amplication#6666] opened 2023-08-11 09:17 UTC
### What happened?

Branch - `next`
I try to up plugin service but I got an error on start

```
 ERROR [ExceptionHandler] Prisma Client could not find its `schema.prisma`. This is likely caused by a bundling step, which leads to `schema.prisma` not being copied near the resulting bundle. We would appreciate if you could take the time to share some information with us.
Please help us by answering a few questions: https://pris.ly/bundler-investigation-error
```

### What you expected to happen

I expect that plugin service should start

### How to reproduce

Checkout latest branch `next` 
try to run `npm run serve:plugins`

### Amplication version

1.8.4

### Environment

node -v
v16.13.0

npm -v
8.1.0

docker -v
Docker version 24.0.2, build cb74dfc

Mac OS
13.4.1 

Env - local

**Comment by abrl91** [comment] 2023-08-11 13:22
duplicate of #6663

**Closed** 2023-08-17 09:04 UTC
Labels: type: bug
