### ISSUE TITLE
Server: Server crash after using prisma 

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#1711] opened 2021-08-29 00:35 UTC
**Describe the bug**
after I start up the server I'm trying to use the client and the server crash

`node[8312]: ../src/node_http_parser.cc:567:static void node::(anonymous namespace)::Parser::Initialize(const FunctionCallbackInfo<v8::Value> &): Assertion `args[3]->IsInt32()' failed.
 1: 0x104ea0d0c node::Abort() [/usr/local/bin/node]
 2: 0x104ea0b8c node::AppendExceptionLine(node::Environment*, v8::Local<v8::Value>, v8::Local<v8::Message>, node::ErrorHandlingMode) [/usr/local/bin/node]
 3: 0x104eba344 node::(anonymous namespace)::Parser::Initialize(v8::FunctionCallbackInfo<v8::Value> const&) [/usr/local/bin/node]
 4: 0x10506fad8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
 5: 0x10506f098 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
 6: 0x10506e898 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
 7: 0x1057e35cc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
 8: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
 9: 0x105779a58 construct_stub_create_deopt_addr [/usr/local/bin/node]
10: 0x10586e578 Builtins_ConstructHandler [/usr/local/bin/node]
11: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
12: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
13: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
14: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
15: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
16: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
17: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
18: 0x105828c98 Builtins_PromiseConstructor [/usr/local/bin/node]
19: 0x105779c90 Builtins_JSBuiltinsConstructStub [/usr/local/bin/node]
20: 0x10586e578 Builtins_ConstructHandler [/usr/local/bin/node]
21: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
22: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
23: 0x1057a96f4 Builtins_AsyncFunctionAwaitResolveClosure [/usr/local/bin/node]
24: 0x10582a81c Builtins_PromiseFulfillReactionJob [/usr/local/bin/node]
25: 0x10579c348 Builtins_RunMicrotasks [/usr/local/bin/node]
26: 0x10577a724 Builtins_JSRunMicrotasksEntry [/usr/local/bin/node]
27: 0x1051407b0 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
28: 0x105140cc0 v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
29: 0x105140d88 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) [/usr/local/bin/node]
30: 0x1051631f4 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) [/usr/local/bin/node]
31: 0x10516302c v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) [/usr/local/bin/node]
32: 0x10506fad8 v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) [/usr/local/bin/node]
33: 0x10506f098 v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) [/usr/local/bin/node]
34: 0x10506e898 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) [/usr/local/bin/node]
35: 0x1057e35cc Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit [/usr/local/bin/node]
36: 0x10577ca38 Builtins_InterpreterEntryTrampoline [/usr/local/bin/node]
37: 0x10577a84c Builtins_JSEntryTrampoline [/usr/local/bin/node]
38: 0x10577a4e4 Builtins_JSEntry [/usr/local/bin/node]
39: 0x105140864 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) [/usr/local/bin/node]
40: 0x10513fe5c v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [/usr/local/bin/node]
41: 0x105009668 v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
42: 0x104defc64 node::InternalCallbackScope::Close() [/usr/local/bin/node]
43: 0x104df0184 node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [/usr/local/bin/node]
44: 0x104e05838 node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [/usr/local/bin/node]
45: 0x104f45870 node::StreamBase::CallJSOnreadMethod(long, v8::Local<v8::ArrayBuffer>, unsigned long, node::StreamBase::StreamBaseJSChecks) [/usr/local/bin/node]
46: 0x104f4786c node::EmitToJSStreamListener::OnStreamRead(long, uv_buf_t const&) [/usr/local/bin/node]
47: 0x104f4bfa4 node::LibuvStreamWrap::OnUvRead(long, uv_buf_t const*) [/usr/local/bin/node]
48: 0x10576a050 uv__stream_io [/usr/local/bin/node]
49: 0x105772144 uv__io_poll [/usr/local/bin/node]
50: 0x1057608fc uv_run [/usr/local/bin/node]
51: 0x104df0bf8 node::SpinEventLoop(node::Environment*) [/usr/local/bin/node]
52: 0x104eda1d4 node::NodeMainInstance::Run(node::EnvSerializeInfo const*) [/usr/local/bin/node]
53: 0x104e76164 node::Start(int, char**) [/usr/local/bin/node]
54: 0x18d75d430 start [/usr/lib/system/libdyld.dylib]`

after I updated the prisma to 2.30 and the nestjs-prisma to 0.13.1 the problem resolved

**Desktop (please complete the following information):**
 - OS: macOS (M1)
 - Browser: firefox

**Comment by yuval-hazaz** [comment] 2021-08-29 09:18
duplicate of #1343

**Closed by yuval-hazaz** 2021-08-29 09:18 UTC
Labels: type: bug
