### ISSUE TITLE
🐛 Bug Report: generate app e2e test crash

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#2294] opened 2022-02-14 10:00 UTC
### What happened?

Test number 55 is crashing even from the master
https://github.com/amplication/amplication/actions/runs/1839907891

### What you expected to happen

The test will pass on the master

### How to reproduce

run the test https://github.com/amplication/amplication/actions/workflows/generated-app-e2e.yml

### Amplication version

0.11.3

### Are you willing to submit PR?

Yes I am willing to submit a PR!

**Comment by mshidlov** [comment] 2022-02-20 07:22
@tupe12334 Thank you for reporting that issue

**Comment by mshidlov** [comment] 2022-02-20 07:25
**HOW TO REPRODUCE:**
```
npm ci
npm run bootstrap -- --loglevel verbose
npm run build -- --scope @amplication/data-service-generator
npm run generate-test-data-service
npm ci && npm run prisma:generate
npm run test:e2e -- --scope @amplication/data-service-generator
```

**Comment by Ash-KODES** [comment] 2022-03-16 11:12
Can I work on it?

**Comment by souravjain540** [comment] 2022-03-16 11:18
> Can I work on it?

Assigned it to you! Have a good time working on it.

**Comment by souravjain540** [comment] 2022-03-16 11:21
> Can I work on it?

this is not that issue. please comment here - https://github.com/amplication/amplication/issues/2411

**Comment by souravjain540** [comment] 2022-05-09 05:36
@tupe12334 this issue is not clear from the last 10 issues for first timers.

Either make it clear or please close it.

**Comment by jainpawan21** [comment] 2022-05-19 04:35
Hi @tupe12334,
I tried to run this workflow in my cloned repository because the links you have mentioned do not have logs now [may be a retention period issue]

This import statement `import getPort from "get-port";` is creating issue

<img width="1511" alt="Screenshot 2022-05-19 at 10 02 23 AM" src="https://user-images.githubusercontent.com/39362422/169205740-290813d5-e590-491a-a273-bd5df8313eae.png">

**Comment by tupe12334** [comment] 2022-05-19 13:31
@jainpawan21 Yes the problem started when we update is to version 6

**Comment by jainpawan21** [comment] 2022-05-20 18:06
Hi @tupe12334,
As per the reply of the get-port library author in [this](https://github.com/sindresorhus/get-port/issues/59) issue and 6.00 version [release notes](https://github.com/sindresorhus/get-port/releases/tag/v6.0.0), get-port is now pure ESM,

Now, We have three options:- 

1. Rollback to previous version 5.1.1 [We can do so because we are using get-port only at one place to get random port].
2. Make amplication esm compatible.
3. Use the alternative of get-port.

**Comment by tupe12334** [comment] 2022-05-22 15:25
@jainpawan21 I think for now we will roll back to 5.1.1

**Comment by jainpawan21** [comment] 2022-05-22 15:26
Ok, I will raise PR to fix the same

**Closed** 2022-05-23 09:41 UTC
Labels: type: bug, good first issue, help wanted, generated server, status: accepted
