### ISSUE TITLE
🐛 Bug Report: incorrect naming for `GitHub` on `Push changes to GitHub` part of code generation

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#6247] opened 2023-06-14 10:34 UTC
### What happened?

<img width="919" alt="image" src="https://github.com/amplication/amplication/assets/73097785/97da21b0-10a7-4b83-a258-696fb1c10124">

### What you expected to happen

Any reference that is `Github` should be changed to `GitHub`.

### How to reproduce

Building any service and looking at the bottom part of the build process will work.

### Amplication version

1.7.2

**Comment by levivannoort** [comment] 2023-06-14 10:36
Things to be changed here:
- title of the code generation section and wording of the product on line 1 & 3 as can be seen in the highlighted section of the `What happend?`

**Comment by vishalpawarR** [comment] 2023-06-14 16:09
@levivannoort In every place of the project it should be changed to the GitHub in URL as well?

**Comment by Amoghtech** [comment] 2023-06-16 09:15
Can i work on this?

**Comment by ganeshpatil386386** [comment] 2023-06-16 10:54
So, This PR is close now?
@souravjain540

**Comment by souravjain540** [comment] 2023-06-19 07:43
@Amoghtech  any updates? are you working on this issue?

**Comment by VaibhavTalkhande** [comment] 2023-06-20 17:51
@souravjain540  can I work on it if the issue is not resolved

**Comment by yashlondhe90960** [comment] 2023-06-21 10:26
Hi @souravjain540 can I work on this issue?

**Comment by Vikash-8090-Yadav** [comment] 2023-06-21 10:33
Please assign me this issue .

**Comment by souravjain540** [comment] 2023-06-21 10:36
assigned to you @yashlondhe90960. let me know if you need any help and when can I expect a PR?

**Comment by yashlondhe90960** [comment] 2023-06-21 11:07
Hi I need some help! 
Can you please point me to some resources where I can understand the issue more and take positive steps towards it?

**Comment by yashlondhe90960** [comment] 2023-06-22 07:03
Hey @souravjain540 I made the required changes but while making a PR it requires some 'Tests for the changes to be added' 
I'm unable to understand what is that, or shall I make a PR ignoring that line?

**Comment by yashlondhe90960** [comment] 2023-06-23 15:38
@souravjain540 I've made the PR can you please check?

**Comment by VaibhavTalkhande** [comment] 2023-06-23 17:32
Hey @yashlondhe90960 as I cannot contribute to this issue because it is for first timers i would recommend you to read contributing guidelines i think that would help you 
[](https://github.com/amplication/amplication/blob/master/CONTRIBUTING.md)

**Comment by yashlondhe90960** [comment] 2023-06-23 18:15
Hey @VaibhavTalkhande I gave a read to Contributing.md and then only made the PR, but if you have any suggestions for me I'm happy to hear from you :)

**Comment by VaibhavTalkhande** [comment] 2023-06-23 18:40
Hey @yashlondhe90960 i think you have missed the part how to create a pull request .see some merged pr you will get idea.
I don't know but that might be the reason your pr is not reviewed yet.

**Comment by VaibhavTalkhande** [comment] 2023-06-23 19:13
> Thanks @VaibhavTalkhande for your inputs, can you please check now if everything seems fine?
> 

Do the necessary changes of branch name, and commit message according to contributing.md
And everything will be good to go and you not face any problem further .

**Comment by yashlondhe90960** [comment] 2023-06-23 19:46
Hi I tried to rename the branch name but the PR got it closed 
![image](https://github.com/amplication/amplication/assets/99034957/8db23d3d-681c-48d1-b329-8c0a3a12056c)
please help me with this, what shall I do next?

**Comment by VaibhavTalkhande** [comment] 2023-06-24 02:20
> Hi @VaibhavTalkhande I tried to rename the branch name but the PR got it closed 
> ![image](https://github.com/amplication/amplication/assets/99034957/8db23d3d-681c-48d1-b329-8c0a3a12056c)
> please help me fixing this, I reopened the PR but not sure what to do next.
> 

Create a new branch in your local and do code changes and commit while doing this take help of contributing.md here each and every step is given(how to create branch and naming and commit message)

**Comment by yashlondhe90960** [comment] 2023-06-24 14:54
Hi @souravjain540 I've completed the task, please check.

**Closed** 2023-08-10 14:29 UTC
Labels: type: bug, good first issue, open to community, first-timers
