### ISSUE TITLE
🐛 Bug Report: Server throws error "TypeError: rxjs_1.lastValueFrom is not a function"

### ISSUE THREAD

**Issue by JohnnyDeeee** [amplication/amplication#4073] opened 2022-10-06 20:06 UTC
### What happened?

Server throws error "TypeError: rxjs_1.lastValueFrom is not a function" when trying to access data from the admin-ui on a brand new project
![image](https://user-images.githubusercontent.com/9005496/194407046-bff79c63-6851-405e-bbc6-08029e42b681.png)

```
[Nest] 2795  - 10/06/2022, 9:54:43 PM   ERROR [ExceptionsHandler] rxjs_1.lastValueFrom is not a function
TypeError: rxjs_1.lastValueFrom is not a function
    at ExternalContextCreator.transformToResult (REDACTED/server/node_modules/@nestjs/core/helpers/external-context-creator.js:152:27)   
    at target (REDACTED/server/node_modules/@nestjs/core/helpers/external-context-creator.js:78:25)
    at REDACTED/server/node_modules/@nestjs/core/helpers/external-proxy.js:9:24
```

### What you expected to happen

Getting at leas the admin user in the Users page in the admin-ui (this is a brand new project without any seeds other than the default admin user)

### How to reproduce

1. Create a new project
2. Follow all the steps in the Server readme to start the database + server
3. Follow all the steps in the Admin-ui readme to start the admin ui
4. Login into the admin ui with the default credentials
5. Open the Users page (or any other page that should load data)
6. Notice that you get an error and no data is fetched from the server

### Amplication version

Where can i find the version? I used https://app.amplication.com/

### Environment

Node version: `v16.17.0`
NPM version: `8.15.0`
Docker version: `Docker version 17.09.0-ce, build afdb6d4`
OS Details (Linux): 
```
NAME="Ubuntu"
VERSION="16.04.7 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.7 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial
Linux REDACTED 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by JohnnyDeeee** [comment] 2022-10-06 20:13
This seems to have fixed it:

```
npm i rxjs@^7
```

from https://stackoverflow.com/questions/68317383/typeerror-rxjs-1-lastvaluefrom-is-not-a-function

This did ad the `rxjs` to my dependencies, so i'm not sure if it is the cleanest solution..

**Comment by yuval-hazaz** [comment] 2022-10-08 07:51
@JohnnyDeeee & @rienheuver thanks foe the info. 
I will assign this to a core member to decided whether we need to add the dependency to the project

**Comment by rienheuver** [comment] 2022-10-12 08:07
https://user-images.githubusercontent.com/9960351/195285754-00400f2b-57ea-4a67-bebe-734e124ef5e5.mp4

@abrl91 I ran your provided zip and still get this error. I use `yarn` btw instead of `npm`, maybe that could be the reason? Didn't try with npm yet. Some other system info:

- Chrome Version 106.0.5249.103 (Official Build) (64-bit)
- yarn v1.22.19
- OS: Ubuntu 20.04.5 LTS
- Laptop: Dell XPS 15 7590

**Comment by rienheuver** [comment] 2022-10-13 12:29
I was just talking about this with a colleague and he mentioned that it could very well be the node version used. Which version are you using @abrl91 ? I just tested it with node 14 and 16, and both get the error. To be more specific:
- v14.18.1 
- v16.18.0
(both LTS)

**Comment by abrl91** [comment] 2022-10-14 12:39
@rienheuver 
node v16.17.1 
npm v8.15.0

**Comment by rienheuver** [comment] 2022-10-14 12:42
In that case I have no clue honestly, I can hardly image the minor version difference in node could be the problem and the npm version shouldn't matter at all I assume. :man_shrugging:

**Comment by yuval-hazaz** [comment] 2022-10-15 09:47
worth looking into the fact that @rienheuver mentioned that he used yarn and not npm

**Comment by abrl91** [comment] 2022-10-20 12:09
@yuval-hazaz @rienheuver I couldn't run the app with `yarn` at all. 

I could run `yarn' to install the dependencies, but then I couldn't run the client and the server. 
They both fell for the fact that they supposedly have no dependencies

**Comment by rienheuver** [comment] 2022-10-25 10:57
Did you use a clean copy of your own zip? For example, deleted any package-lock.json files and node_modules/ ? Because I downloaded your zip, ran `yarn` and then `yarn start` and it works. Except of course for the bug this issue is about ;-)

**Comment by yuval-hazaz** [comment] 2022-10-31 03:19
@abrl91 any update on this issue? Should we assign it to someone else?

**Comment by abrl91** [comment] 2022-10-31 07:38
@rienheuver @yuval-hazaz @JohnnyDeeee 
I couldn't reproduce it. With `yarn` it doesn't work for me at all, even on a clean-generated app. I ran `yarn` to install the dependencies and if it failed in the end.

**Comment by rienheuver** [comment] 2022-11-01 12:28
What do you mean with "it doesn't work at all"? Because unless you've found a bug in yarn, that sounds like a local issue to your machine

**Comment by thinktapper** [comment] 2022-11-19 22:27
> This seems to have fixed it:
> 
> ```
> npm i rxjs@^7
> ```
> 
> from https://stackoverflow.com/questions/68317383/typeerror-rxjs-1-lastvaluefrom-is-not-a-function
> 
> This did ad the `rxjs` to my dependencies, so i'm not sure if it is the cleanest solution..

This also fixed it for me

**Comment by abrl91** [comment] 2022-11-20 07:23
Thank you @thinktapper

**Closed** 2024-09-02 15:02 UTC
Labels: type: bug
