### ISSUE TITLE
Name conversion in message broker 

### ISSUE THREAD

**Issue by tupe12334** [amplication/amplication#3835] opened 2022-09-15 13:27 UTC
When you create a new message broker topic, the name is automatically converted to camelCase format
<img width="865" alt="Screen Shot 2022-09-15 at 16 27 44" src="https://user-images.githubusercontent.com/61761153/190416050-a54d5264-bd30-4417-948b-25405b744666.png">

**Comment by b4s36t4** [comment] 2022-09-16 10:44
What do we need to do here? @tupe12334

**Comment by arielweinberger** [comment] 2022-09-16 11:58
Duplicate of #3762  which has been fixed in #3838. Closing.

**Closed by arielweinberger** 2022-09-16 11:58 UTC
