### ISSUE TITLE
Cannot delete roles



### ISSUE THREAD

**Issue by GalCegla** [amplication/amplication#1079] opened 2020-12-30 14:50 UTC
**Bug description**
Cannot delete a role, there is no such option.

**Expected behavior**
To be able to delete roles.

**Comment by mayhemlikemee** [comment] 2021-02-01 19:56
Also experiencing this same issue.

**Comment by yuval-hazaz** [comment] 2022-07-23 14:52
duplicate of https://github.com/amplication/amplication/issues/2370

**Closed by yuval-hazaz** 2022-07-23 14:52 UTC
Labels: type: bug
