### ISSUE TITLE
UX:  Add text to the Base Directories page 

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#3442] opened 2022-08-14 17:30 UTC
### Describe the issue with documentation

The Base Directories page does not include any explanatory text. 

![image](https://user-images.githubusercontent.com/96979533/184547877-9a6df22a-2e0d-4222-83b2-f77ac5a1ce8c.png)

### How to solve the problem

Create a short text of one or two sentences to explain the purpose of the Base Directories.

The Docs  article could provide some ideas:

https://docs.amplication.com/docs/how-to/custom-code/#the-base-folder

**Comment by Rutam21** [comment] 2022-10-04 06:29
@yuval-hazaz @souravjain540 I would love to work on this. Please assign this to me. Also it would be great if you can point me to the folder where the change needs to be done. Thanks.

**Comment by TheLearneer** [comment] 2022-10-19 17:14
@MoFoGo I believe the issue is resolved, so can be closed?
cc: @souravjain540

**Closed** 2022-10-31 02:10 UTC
Labels: type: bug, type: docs, good first issue, open to community
