### ISSUE TITLE
🐛 Bug Report: Autogenerated @isJson Validator for created Json-fields does not allow valid input in Request body

### ISSUE THREAD

**Issue by vincenzodomina** [amplication/amplication#4223] opened 2022-10-21 12:10 UTC
### What happened?

Autogenerated @isJson Validator from class-validator for created Json-fields does not allow valid objects in request body and throws error:

property must be a string!

Autogenerated DTO entry:

```
  @ApiProperty({
    required: false,
  })
  @IsJson()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  reference_urls?: JsonValue;
```

My workaround with correct behaviour: remove the @IsJson() decorator, but i added some other validation to have some custom validation:

```
  @ApiProperty({
    required: false,
  })
  @IsArray()
  // "each" tells class-validator to run the validation on each item of the array
  @IsString({ each: true })
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  reference_urls?: JsonValue;
```

### What you expected to happen

When adding the following input to a request body, it should not throw an error and pass it to prisma:

```
{
...
  "reference_urls": [
    "https://www.web.com/",
    "https://www.test.com/"
  ],
...
}
```

Since I want to store arrays of strings I have to use Json fields which is great concerning the postgres and prisma related parts, but the autogenerated @isJson validator prevents to work with it

So I think the solution would be to remove the autogenerated   @IsJson() decorator and maybe even add a feature to add more specific validation (if it is array, object or string, or custom DTO, etc..)

### How to reproduce

-Create an Entity with a Json field
- pass an array of string in the Create or Update route request body property

### Amplication version

1.0.2

**Comment by souravjain540** [comment] 2022-10-25 07:51
@tupe12334 can you help?

**Comment by yuval-hazaz** [comment] 2022-10-31 02:53
@arielweinberger @tupe12334 please review

**Comment by tupe12334** [comment] 2022-10-31 08:35
Hi @vincenzodomina I tried to reproduce the problem and was not able to, I can enter an array of strings into JSON field; can you provide more details, please?
What is the error message?

**Comment by amirping** [comment] 2022-11-15 21:04
having the same issue after the change of the role field in the user entity, sending an array of string like ['admin'], causing a bad request exception.

**Comment by yuval-hazaz** [comment] 2022-11-16 07:00
@amirping can you share a link to a repo with the generated code so we can reproduce the issue?

**Comment by vincenzodomina** [comment] 2022-11-16 08:43
> 

Sure, here is the error:
![image](https://user-images.githubusercontent.com/54762917/202130696-c03f27d7-e46c-4397-b27f-8f4136554ed3.png)

I created a test application here: https://github.com/vincenzodomina/amplication-test-app
- I used the sample order service app 
- I added a property named "links" to the "product" entity with the json data type
- On posting a product with an array of strings in the links property this error shows up

**Comment by tupe12334** [comment] 2022-11-17 10:10
Hi @vincenzodomina just want to say that I got your comment, and one thing I noticed is that I tested that with graphql and not the rest API and it worked for me. I will test the rest API shortly

**Comment by tupe12334** [comment] 2022-11-20 14:47
UPDATE:
@vincenzodomina Please see in the class-validator [docs](https://github.com/typestack/class-validator/blame/develop/README.md#L862) that IsJson is checking first if you send a string, and then check if it can be parsed to a JSON object.
You send an array in the first place, not a string, and its crashes because of that.
We have three options
- To leave it as an IsJson decoration
- To change it to IsObject decoration to accept objects only
- To add a custom decoration that can get a string or a JSON valid data

Just want to mention that the logic of the graphql is to accept every valid JSON data (string, array, number etc...)

I will be happy to hear your input about the solution.

**Comment by vincenzodomina** [comment] 2022-11-22 12:54
> UPDATE: @vincenzodomina Please see in the class-validator [docs](https://github.com/typestack/class-validator/blame/develop/README.md#L862) that IsJson is checking first if you send a string, and then check if it can be parsed to a JSON object. You send an array in the first place, not a string, and its crashes because of that. We have three options
> 
> * To leave it as an IsJson decoration
> * To change it to IsObject decoration to accept objects only
> * To add a custom decoration that can get a string or a JSON valid data
> 
> Just want to mention that the logic of the graphql is to accept every valid JSON data (string, array, number etc...)
> 
> I will be happy to hear your input about the solution.

Thanks!
So, to add a custom decorator for the REST API that matches the GraphQL logic would be the preferred solution. (New feature: Change autogenerated decorator)

For me in my case adding the @isObject or @isArray decorators, partly with nested Validation  @IsString({ each: true }), did the trick for more validation of what is expected inside the JSON, but it involves changing autogenerated code in the base controllers. (Maybe possible feature to add preferred Validation from UI)

**Comment by yuval-hazaz** [comment] 2022-12-03 08:25
@arielweinberger @overbit @tupe12334 
let's make a decision about how we want to proceed from here. 
WDYT?

**Comment by amirping** [comment] 2022-12-09 14:34
in my case the issue was bizarre, the role in the user entity was @isJson, is supposed to be @isArray. i did fix that and it's working now.

**Comment by yuval-hazaz** [comment] 2022-12-17 08:15
@GreenMachine01 I assigned this one to you so we can prioritize and add to the backlog

**Closed** 2023-04-27 16:08 UTC
Labels: type: bug, impact: Productivity, Sapphire
