### ISSUE TITLE
🐛 Bug Report:  Minor UI Fixes on the main page

### ISSUE THREAD

**Issue by abrahamvg** [amplication/amplication#7308] opened 2023-10-21 17:20 UTC
### What happened?

There is a minor UI Fix that should be done on [amplication homepage](https://amplication.com/)

UI Bug :
![image](https://github.com/amplication/amplication/assets/60133406/17acca44-8e04-4c9c-b215-b1dc3464dab2)

Description :
_Generate Production-Ready_ gets hidden under the Navbar

### What you expected to happen

The Text should be below the Navbar and Version 

### How to reproduce

1. Open the website in responsive mode
2. Use Dimensions as _Iphone 12 Pro_ 

### Are you willing to submit PR?

_Yes_

**Comment by lalitkumawat1m** [comment] 2023-10-22 00:54
hey @GreenMachine01, I want to work on this issue please assign to me

**Comment by GreenMachine01** [comment] 2023-10-22 08:52
Closing as duplicate of - https://github.com/amplication/amplication/issues/7287

**Closed by GreenMachine01** 2023-10-22 08:52 UTC
Labels: type: bug
