### ISSUE TITLE
🐛 Bug Report: MySQL Plugin Settings do not save

### ISSUE THREAD

**Issue by MichaelSolati** [amplication/amplication#5873] opened 2023-04-25 19:07 UTC
### What happened?

When enabling the MySQL plugin, when I go to edit the settings I get a 400 error and my settings do not save.

![image](https://user-images.githubusercontent.com/11811422/234377892-52cf2586-6308-44a2-99bd-948173f33316.png)

### What you expected to happen

My MySQL settings should save.

### How to reproduce

Install MySQL plugin, go to settings, edit them and try to save.

### Amplication version

1.5.3

**Comment by mulygottlieb** [comment] 2023-05-02 07:54
Closing: Duplicate of #5536

**Closed by mulygottlieb** 2023-05-02 07:54 UTC
Labels: type: bug
