### ISSUE TITLE
[Data Service Generator]: [GENERATED CODE - DO NOT MODIFY BY HAND] for files that are not recommended to be modified

### ISSUE THREAD

**Issue by sandbox-apps** [amplication/amplication#1677] opened 2021-07-20 15:50 UTC
**Is your feature request related to a problem? Please describe.**
There should be a warning for the user about the base files
Maybe on top of the file

// **************************************************************************
// GENERATED CODE - DO NOT MODIFY BY HAND
// **************************************************************************

Something like this. So that no newcomers will ever do such thing :)

**Comment by yuval-hazaz** [comment] 2021-07-21 10:23
duplicate of #1345

**Closed by yuval-hazaz** 2021-07-21 10:23 UTC
Labels: type: feature request
