### ISSUE TITLE
🐛  Bug Report: typo on the README - contributer => contributor

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#7373] opened 2023-11-02 09:51 UTC

**Comment by balagowda** [comment] 2023-11-02 10:09
hey 👋 ! i would like to work on this where exactly the issue is??

**Comment by Hrishi000001** [comment] 2024-02-09 09:09
Hey ,
I would like to work on this issues.

**Comment by sagarkori143** [comment] 2024-02-18 15:59
Hey @PazYanoverr I think we should close the issues which have been resolved. This creates a confusion to the new contributors.

**Comment by PazYanoverr** [comment] 2024-02-18 16:03
Agree, @sagarkori143 - thanks!
@abrl91 @mulygottlieb - Can you please close this issue?

**Closed** 2024-02-26 06:33 UTC
Labels: good first issue, open to community
