### ISSUE TITLE
As User - I want Git-related texts and icons to be more generic or specific to the provider I have chosen

### ISSUE THREAD

**Issue by GreenMachine01** [amplication/amplication#5514] opened 2023-03-21 14:27 UTC
As User - I want Git-related texts and icons to be more generic or specific to the provider I have chosen so that I can easily identify which Git provider I am working with and have a consistent and clear understanding of the Git-related actions I can take within the application.

**Requirements:**

**Comment by abrl91** [comment] 2023-05-17 12:55
@GreenMachine01 
This was already done. We only need an icon for Bitbucket (a white one), but the logic was already implemented and this is in prod. For now we are just using a generic git icon for Bitbucket

**Comment by GreenMachine01** [comment] 2023-05-17 14:07
@abrl91 sounds great. we will need to make sure just that we didn't miss anything and after updating the icon image I might be able to delete this user story

**Comment by abrl91** [comment] 2023-05-18 09:08
Duplicate of:
https://github.com/amplication/amplication/issues/5971
https://github.com/amplication/amplication/issues/5513

**Closed by abrl91** 2023-05-18 09:08 UTC
Labels: epic: Bitbucket, impact: User Experience
