### ISSUE TITLE
🐛 Bug Report: Cannot discard changes for newly created service (User entity is reserved)

### ISSUE THREAD

**Issue by arielweinberger** [amplication/amplication#4990] opened 2023-01-17 15:38 UTC
### What happened?

While testing #4334 and trying to discard changes for a new service, discarding does not work due to the following error:

Instead, I need to manually delete the service.

![image](https://user-images.githubusercontent.com/4976416/212942057-f8d7fd87-15bb-460e-a35d-8f14f08d3001.png)

### What you expected to happen

Entities to be discarded

### How to reproduce

- Create a new service
- Click on "Discard Changes"

### Environment

Next

**Comment by endalk200** [comment] 2023-03-09 08:24
I want to take on this issue if it is not taken.

**Comment by souravjain540** [comment] 2023-03-09 08:50
@endalk200 assigned you another issue

**Comment by aaaaayushh** [comment] 2023-03-09 12:15
Hello can I try working on this?

**Comment by souravjain540** [comment] 2023-03-09 13:46
@aaaaayushh for sure, let us know if you need some help

**Comment by aaaaayushh** [comment] 2023-03-13 05:42
Hello, I've found the concerned code for this issue.
```
async deleteOneEntity(
    args: DeleteOneEntityArgs,
    user: User
  ): Promise<Entity | null> {
    return await this.useLocking(args.where.id, user, async (entity) => {
      if (entity.name === USER_ENTITY_NAME) {
        throw new ConflictException(DELETE_ONE_USER_ENTITY_ERROR_MESSAGE);
      }
```
This seems intentional, but I can't be sure because I don't know the logic behind this code. Can someone help me out?

**Comment by souravjain540** [comment] 2023-03-14 07:11
@EugeneTseitlin can you please help him?

**Comment by abrl91** [comment] 2023-03-18 09:20
@aaaaayushh delete entity triggered by this button:
![Screenshot 2023-03-18 at 11 17 51](https://user-images.githubusercontent.com/39680385/226096855-b7d148ff-e964-42b7-a999-941d43a7c167.png)

This bug is related to the discard changes button:
![Screenshot 2023-03-18 at 11 19 26](https://user-images.githubusercontent.com/39680385/226096929-2ad00584-74f5-401c-ac75-cf9bcec6ac33.png)

**Comment by abrl91** [comment] 2023-03-18 09:36
@aaaaayushh have a look at this screen recording
only when I deleted the newly created entity from its page I got this error.
When I deleted it from the entities page, I didn't get any error.

https://user-images.githubusercontent.com/39680385/226097587-2bc6efcc-c3d0-4a3f-b873-ea7637db3bb9.mov

**Comment by abrl91** [comment] 2023-03-18 09:45
@aaaaayushh actually, now I see that this function is being called here: (entity.service => discardPendingChanges)
![image](https://user-images.githubusercontent.com/39680385/226098016-2709d868-f5e9-4f5b-88c8-c92e3df482e4.png)

**Comment by yuval-hazaz** [comment] 2023-03-18 11:04
This issue is a duplicate of https://github.com/amplication/amplication/issues/5055
Please see the comment on the other issue - we should wait with this fix until we add support to delete the user entity 

I will close this as duplicate of https://github.com/amplication/amplication/issues/5055

**Closed** 2023-03-18 11:06 UTC
Labels: type: bug, TIFT, open to community
