### ISSUE TITLE
🐛 Bug Report: Server is failing in Next env

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#4725] opened 2022-12-21 23:36 UTC
### What happened?

Here is a log from server:
[Nest] 1  - 12/21/2022, 11:34:10 PM   ERROR [ExceptionHandler] ENOENT: no such file or directory, open '/app/schema.prisma'
Error: ENOENT: no such file or directory, open '/app/schema.prisma'
    at Object.openSync (node:fs:600:3)
    at Object.readFileSync (node:fs:468:35)
    at new LibraryEngine (/app/main.js:31945:45)
    at PrismaService.getEngine (/app/main.js:36384:24)
    at new PrismaClient (/app/main.js:36354:37)
    at new PrismaService (/app/main.js:59266:21)
    at Injector.instantiateClass (/app/node_modules/@nestjs/core/injector/injector.js:330:19)
    at callback (/app/node_modules/@nestjs/core/injector/injector.js:48:41)
    at async Injector.resolveConstructorParams (/app/node_modules/@nestjs/core/injector/injector.js:122:24)
    at async Injector.loadInstance (/app/node_modules/@nestjs/core/injector/injector.js:52:9)

### What you expected to happen

Server should run.

### How to reproduce

See next env.

**Comment by overbit** [comment] 2022-12-22 11:45
Duplicate of #4704

**Closed** 2022-12-22 14:17 UTC
Labels: type: bug
