### ISSUE TITLE
🐛 Bug Report: icon is stretched and not circle as the rest

### ISSUE THREAD

**Issue by MatanForU** [amplication/amplication#3616] opened 2022-08-29 07:59 UTC
### What happened?

looks like the icon got a little bit of stretch
<img width="321" alt="Screen Shot 2022-08-29 at 10 56 09" src="https://user-images.githubusercontent.com/8940907/187152914-52d274ab-1ff8-4b78-aa8c-b30febea838e.png">

### What you expected to happen

i guess it suppose to be a circle

### How to reproduce

.

### Amplication version

0.15.0

**Comment by souravjain540** [comment] 2022-08-29 08:01
Thanks for reporting it @MatanForU  💜 

Glad to see you here again :)

please confirm it @alexbass86

**Comment by arielweinberger** [comment] 2022-08-29 08:06
Duplicate of #3579

**Closed by arielweinberger** 2022-08-29 08:06 UTC
Labels: type: bug
