### ISSUE TITLE
Mongo DB support

### ISSUE THREAD

**Issue by deejoe79** [amplication/amplication#3943] opened 2022-09-22 12:54 UTC
### Feature description

Do you plan to consider a document database (NoSQL) support in the future? Like Mongo DB? 

### Use case

I find the NoSQL DBs a bit more flexible for many purposes, I use them with NestJS already in my side projects. This app would be just perfect with Mongo.

**Comment by arielweinberger** [comment] 2022-09-22 14:03
Closing as this is a duplicate of  #1959.

It's definitely on our roadmap. We will soon have thorough documentation on plugin development, so community members who are up for it, will be able to create this as plugin and feature it as an official plugin.

**Closed by arielweinberger** 2022-09-22 14:03 UTC
Labels: type: feature request
