### ISSUE TITLE
Add Granular permissions to different users on the field level

### ISSUE THREAD

**Issue by wfdigitalsupport** [amplication/amplication#1271] opened 2021-03-08 18:00 UTC
On the permissions tab when adding granular permissions on a specific field, will it be possible to set different filed level permissions for different user groups?

at the moment it justs holds the last selected user group when field lever permissions are set. 

Hopefully a quick update 👍

**Comment by yuval-hazaz** [comment] 2021-03-08 18:09
@wfdigitalsupport if I understand correctly, what you are describing is a bug. 
You should be able to select multiple groups per fields 

have a look at #1193. is that what you experiencing? 
If so, we should be able to prioritize and add this to the next sprint

**Comment by wfdigitalsupport** [comment] 2021-03-09 09:24
@yuval-hazaz thats it

**Comment by yuval-hazaz** [comment] 2021-03-09 09:29
Ok! we will take care of it
I will close this as a duplicate of #1193

**Closed by yuval-hazaz** 2021-03-09 09:29 UTC
Labels: type: feature request
