### ISSUE TITLE
🐛 Bug Report: After upgrading to Pro Plan it is not visual in the client

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#5233] opened 2023-02-17 15:34 UTC
### What happened?

After upgrading to Pro Plan it is not visual in the client:
- the message of limitation still appear
- without refreshing the workspace plan still seems like the user is in a free plan

### What you expected to happen

everything should be updated after upgrading to Pro Plan meaning that the user shouldn't see the message about limitations and the workspace plan in the workspace dropdown should be Pro and not Free

### How to reproduce

upgrade your workspace to Pro

### Amplication version

next

**Comment by overbit** [comment] 2023-02-17 15:36
https://user-images.githubusercontent.com/2861984/219697855-1e016e9e-448e-4fa0-817f-d1aa522ed594.mov

**Comment by overbit** [comment] 2023-02-17 15:40
@GreenMachine01  @EugeneTseitlin the issue is  related to the missing hide-notification feature in pro/enterprise plans.

Moreover, there is a potential additional issue related to stigg sdk cache. It seems that we need to refresh stigg data on plan upgrade:

https://github.com/stiggio/stigg-example-todos/blob/master/apps/client/src/app/components/paywall/StiggPaywall.tsx#L59

**Comment by EugeneTseitlin** [comment] 2023-02-19 15:35
The first problem, which is 'the message of limitation still appear' arises from improper condition for showing a notification. It was fixed by the following PR in a context of another issue:
https://github.com/amplication/amplication/pull/5236
https://github.com/amplication/amplication/issues/5227

The first problem, which is 'without refreshing the workspace plan still seems like the user is in a free plan' is already covered by another issue:
https://github.com/amplication/amplication/issues/4845

This issue is closed as a duplicate/combination of two other issues.

**Closed** 2023-02-21 08:52 UTC
Labels: type: bug
