### ISSUE TITLE
Server: User-Role renaming

### ISSUE THREAD

**Issue by timhuebener** [amplication/amplication#1313] opened 2021-04-09 20:07 UTC
**Describe the bug**
When you rename the user-role to something else the DB seed does not work. 

**To Reproduce**
1. Go to Roles
2. Click on User-Role
3. Rename to name: admin, display-name: admin
4. Application won't run

**Expected behavior**
The best option would be to automatically update the role of the initial admin user.
Otherwise at least show a warning.

**Comment by yuval-hazaz** [comment] 2021-04-10 06:37
thanks @timhuebener

**Comment by comixtrip** [comment] 2022-10-01 11:29
Hi, i'm willing to take a look at this issue. Pls confirm that there are no other people already work on that so I can start right away.

**Comment by yuval-hazaz** [comment] 2022-10-01 15:07
@comixtrip i am assigning you. Good luck. We would love to support on discord if needed

**Comment by itsnoa04** [comment] 2023-05-14 01:15
@comixtrip are you still working on it? if not @yuval-hazaz, I'd love to take a look at it.

**Comment by xonx4l** [comment] 2023-11-23 04:30
can you reassign to me @yuval-hazaz .

**Comment by yuval-hazaz** [comment] 2024-05-25 16:56
closing this issue since it is outdated and the code has changed significantly since the ticket was created.
in case this issue remain, we should open a new ticket with details to reproduce

**Closed by yuval-hazaz** 2024-05-25 16:56 UTC
Labels: type: bug, priority: high, status: confirmed
