### ISSUE TITLE
🐛 Bug Report: plugin category 'CI/CD' not showing any plugins

### ISSUE THREAD

**Issue by levivannoort** [amplication/amplication#7653] opened 2023-12-19 11:17 UTC
### What happened?

When selecting the `CI/CD` category on the plugin catalog, it is expected to show the 'Helm Chart' plugin as this is supossed to be tagged with `CI/CD`.

Helm charts with `CI/CD` attached category in the `Kubernetes` category OR in the `AWS` category:
![image](https://github.com/amplication/amplication/assets/73097785/76aa5e79-5d9b-471c-9eb5-82389995690e)
![image](https://github.com/amplication/amplication/assets/73097785/c083c6a9-0765-40eb-9cd6-25946751a1e3)

Empty `CI/CD` category:
![image](https://github.com/amplication/amplication/assets/73097785/db6f1f11-650b-420d-90f2-b6ba765e956e)

### What you expected to happen

To have the `CI/CD` category be filled as with the others.

### How to reproduce

Navigate to the `CI/CD` section.

The problem might be related to the `/` in the name > url.

### Amplication version

1.12.2

**Comment by barshimi** [comment] 2023-12-19 12:13
did you try to write the category with lower case ?

**Comment by barshimi** [comment] 2023-12-19 12:15
please change the category name to ci-cd instead of ci/cd. it's not a bug, it's naming convention

**Comment by mulygottlieb** [comment] 2023-12-19 12:57
@barshimi - The choice of category names is a product choice, not an engineering choice. And if Paz wants the category to be named "CI/CD" there is no reason we will not support it.
The only exception to this is if we find out that supporting this means X hours of work, which we feel is excessive for the value, we can bring it back to Paz to tell him, "This will take two X to fix. Is it worth it, or do you want us to change the category name instead"?

So, I would be happy to get an estimation for supporting category names with escapable characters like "/" and if the estimation is high we will go and re-consult with @PazYanoverr regarding the category name.

**Comment by varsubham** [comment] 2023-12-20 17:07
@levivannoort @barshimi I have raised a fix for this, please review if this looks fine

Thanks

**Comment by overbit** [comment] 2023-12-27 12:05
## Test result: ✅ 

![Image](https://github.com/amplication/amplication/assets/2861984/7d1e6ba8-442c-483d-b806-4d00e94a1ae5)

**Closed** 2024-04-15 12:39 UTC
Labels: type: bug
