### ISSUE TITLE
🐛 Bug Report:  Windows has a problem with :

### ISSUE THREAD

**Issue by hridaya423** [amplication/amplication#4171] opened 2022-10-16 19:09 UTC
### What happened?

With the starter app, There is a lot of commands that have a : in them,

But they don't work in windows as windows takes that as invalid syntax 

I found a quick fix for it, go to the package.json and change the commands but that does not work with docker compose

I changed it in dockerfile the prisma generate command but it still has some problems

Here's proof of it in my Introduction to Amplication Video: https://youtu.be/VCU1hOnSA6k

### What you expected to happen

I don't what I expected to Happen

I just expected it to work

### How to reproduce

Download the latest Sample Service of Order Management

### Amplication version

The Latest one

### Environment

Node: v16.18.0
NPM: 8.13.0
Docker: v20.10.17
OS: Windows 11 Insider Preview

**Comment by souravjain540** [comment] 2022-10-17 08:42
Can you add screenshots? @hridaya423

**Comment by yuval-hazaz** [comment] 2022-10-18 18:43
@EugeneTseitlin can you have a look at this and share your thoughts ?

**Comment by ridays2001** [comment] 2022-10-23 05:51
Cannot reproduce this

**Comment by hridaya423** [comment] 2022-10-23 09:03
Does VS Code use a different terminal than Powershell?

**Comment by arielweinberger** [comment] 2022-10-23 10:22
@yuval-hazaz  If this is indeed confirmed by @EugeneTseitlin we should consider how it is affected by the switch to Nx, so that we don't do double work.

@EugeneTseitlin as requested, could you please check and verify if you can reproduce?

**Comment by EugeneTseitlin** [comment] 2023-02-05 12:56
@GreenMachine01 should I try to reproduce it? I think the product has changed significantly from the point when but was reported.

**Comment by GreenMachine01** [comment] 2023-02-12 17:22
@EugeneTseitlin if you can try to reproduce it in less than 10 minutes let's check if we can close this issue or if it still needs to be fixed.

**Comment by yuval-hazaz** [comment] 2024-09-02 15:03
closed due to inactivity

**Closed by yuval-hazaz** 2024-09-02 15:03 UTC
Labels: type: bug
