### ISSUE TITLE
🐛 Bug Report: on dev environment - admin-ui failed when running npm run start

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#2415] opened 2022-03-09 19:22 UTC
### What happened?

Dev environment only!
On amplication-data-service-generation, after running "generate-test-data-service" script we get 'generated' folder.
There, on admin-ui folder running npm i and then npm run start it throws the following error

![image](https://user-images.githubusercontent.com/39680385/157514196-651a9e74-2967-41e6-8c0b-0f7a6280e8d4.png)

### What you expected to happen

npm run start to run successfully

### How to reproduce

- run the development setup
- on amplication-data-service-generation run: npm run generate-test-data-service
- on terminal: get into the amplication-data-service-generation/generated/admin-ui path
- run npm i and then npm run start
- see the error

### Amplication version

12.0.0

### Environment

node version 16.3.0
npm version 7.15.1
docker version 20.10.12
macOS

**Comment by yuval-hazaz** [comment] 2022-03-10 05:18
@abrl91 this is a classic case of “it’s not a bug, it’s a feature”
Since the generated app is created in a sub folder within the DSG folder, the parent node modules folder cause a conflict.

you should add SKIP_PREFLIGHT_CHECK=true  in the command line just before ‘npm i’

**Comment by yuval-hazaz** [comment] 2022-03-10 08:26
@abrl91 please confirm that this is the issue you were talking about, and that the method I suggested works for you
if so, we will close this issue

**Comment by abrl91** [comment] 2022-03-10 08:30
@yuval-hazaz added to my todo list :) I will check it later and update/close this issue

**Comment by abrl91** [comment] 2022-03-10 11:31
@yuval-hazaz  run SKIP_PREFLIGHT_CHECK=true npm run start on admin-ui works

**Closed** 2022-03-10 11:31 UTC
Labels: type: bug
