### ISSUE TITLE
Server: Datatype number enable auto-increment and start from number

### ISSUE THREAD

**Issue by alonram** [amplication/amplication#1018] opened 2020-12-16 14:21 UTC
Datatype number to be able to increment by 1 or by x everytime a new record is created and starting number. Can be used when creating orders entity so we can use it as order ID for the customer.

**Comment by yenicelik** [comment] 2021-05-22 23:21
related: https://github.com/amplication/amplication/issues/1342

**Comment by yuval-hazaz** [comment] 2021-05-23 08:32
Closed as duplicate of #1342

**Closed by yuval-hazaz** 2021-05-23 08:32 UTC
Labels: type: feature request
