### ISSUE TITLE
🐛 Bug Report: typo in `dist_modules` (instead of node_modules)

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#4848] opened 2023-01-05 11:15 UTC
typo in `dist_modules` (instead of node_modules)
other than that, the plugin is working.

![image](https://user-images.githubusercontent.com/39680385/210264978-c74adde1-b48e-437a-af49-fae12ad6e849.png)

_Originally posted by @abrl91 in https://github.com/amplication/amplication/issues/4451#issuecomment-1369118444_

### Plan
Add method "addFile" to DSG that would check if the file already exists and issue notification
New file should override previous file.
When writing files to file system add option to override duplicated files.

**Comment by EugeneTseitlin** [comment] 2023-01-08 08:52
Just correct folder.

**Comment by EugeneTseitlin** [comment] 2023-01-10 12:17
The issue is related to merge strategy between files from dsg and plugins. File from plugin merged with file from dsg, instead of override.

DSG .prettierignore:
node_modules/
dist/
prisma/migrations/
package-lock.json
coverage/

Prettier Plugin .prettierignore:
dist

**Comment by EugeneTseitlin** [comment] 2023-01-10 15:09
Currently binary file merge is a default strategy for resolving files with the same path. In my opinion it has to be at least override or append. There are already several use cases that are based on current behavior, so changing it will cause extensive validation.

**Closed** 2023-06-13 16:02 UTC
Labels: type: bug
