### ISSUE TITLE
🐛 Bug Report: Disconnect an organization is not reflected in the organizations selector 

### ISSUE THREAD

**Issue by abrl91** [amplication/amplication#3606] opened 2022-08-28 06:53 UTC
### What happened?

In sync with GitHub page, when a user disconnects an organization, it is not reflected in the selector

![image](https://user-images.githubusercontent.com/39680385/187061341-6bb90df2-3956-489c-924c-8dc61ea6bff6.png)

### What you expected to happen

I expect that when a user disconnects an organization, it will not appear in the selectordisconnects

### How to reproduce

- go to sync with GitHub page
- if you didn't sync before, connect your account/organization
- try to connect a new organization, but this time, click on `configure`
![image](https://user-images.githubusercontent.com/39680385/187061464-13c96171-956d-4f2c-8599-ac59bf9dacf5.png)
at the bottom of the page, you will see disconnect, click on that
- go back to Amplication, and see that your organization still appears in the selector

### Amplication version

0.15.0

**Comment by jainpawan21** [comment] 2022-09-03 13:52
@abrl91 this Configure option will be visible to new organisations only or old ones also?
I am not able to see this option in 0.15.2 version

**Comment by lokeswaran-aj** [comment] 2023-02-17 17:44
Hi, @abrl91 I was researching this issue. And a solution to fix it. We can use Github Webhook and put an HTTPS URL as shown below. 
<img width="785" alt="Screenshot 2023-02-17 at 11 06 30 PM" src="https://user-images.githubusercontent.com/74011196/219728760-45902463-bb2a-45d6-8e04-a084744e1fbf.png">

GitHub will send a POST request when a user uninstalls the Amplication app from GitHub.
<img width="936" alt="Screenshot 2023-02-17 at 11 09 35 PM" src="https://user-images.githubusercontent.com/74011196/219729911-ca5fa794-d82f-4e01-ac62-e18e35991b2a.png">

Whenever the body has the action as `delete` we can remove that organization from our workspace org list.

What do you think about this approach?

reference : [GitHub Webhook events](https://docs.github.com/webhooks-and-events/webhooks/webhook-events-and-payloads?actionType=deleted#installation)

**Comment by abrl91** [comment] 2023-02-20 06:42
Thank you @lokeswaran-aj

**Comment by lokeswaran-aj** [comment] 2023-02-20 15:21
@abrl91 Do you think the community or me can contribute to this or does the Amplication team need to make a decision?

**Comment by souravjain540** [comment] 2023-06-22 06:42
@GreenMachine01  is this issue still relevant?

**Comment by GreenMachine01** [comment] 2023-06-22 07:26
@souravjain540 I think this is a duplicate of - https://github.com/amplication/amplication/issues/4957
in this case, we can close this item and keep the other ticket which is already being worked on.

**Closed** 2023-06-22 07:27 UTC
Labels: type: bug, good first issue, @amplication/git-service, open to community
