### ISSUE TITLE
🐛 Bug Report: TypeError: defaultDataProvider is not a function

### ISSUE THREAD

**Issue by divich** [amplication/amplication#2352] opened 2022-02-23 15:57 UTC
### What happened?

Started the server and then started the client for the sample app in docs

After i logged in, the refresh icon keeps on spinning forever and no data is being shown, when i click in users section.

![Screenshot 2022-02-23 211515](https://user-images.githubusercontent.com/18300716/155355030-1332ed0b-1f7f-4ba0-ad81-71a2b34b16ed.png)

### What you expected to happen

wanted the sample app to run

### How to reproduce

start the sample app as in docs on windows 11.

**Comment by yuval-hazaz** [comment] 2022-02-24 06:45
@mshidlov @tupe12334 
I saw a discussion on Discord for the same issue. We need to check if this issue can be reproduced and how

https://discord.com/channels/757179260417867879/781089015548870695/944596244804808754

**Comment by yuval-hazaz** [comment] 2022-03-06 07:46
@mshidlov this should be a candidate for 12.1

**Comment by tupe12334** [comment] 2022-03-06 14:21
@divich i'm an able to reproduce the problem, can you elaborate more on the process that led you to this problem?
If you want we can go to a zoom call together

**Comment by yuval-hazaz** [comment] 2022-03-06 17:47
@tupe12334 please reach out on discord - there were multiple reports of this issue in the support channel. 
Also, talk with @0xsapphir3 who mentioned that he already had this problem

**Comment by tupe12334** [comment] 2022-03-10 08:20
We pinpoint the problem.
The problem accrues because of the use of yarn instead of npm to do the packages installation.

**Comment by tupe12334** [comment] 2022-03-10 08:22
@mshidlov how do you want to proceed?
1. block the use of yarn via the package.json engine section?
2. Add in the doc big comment that said "We are not support yarn"

**Comment by yuval-hazaz** [comment] 2022-03-10 08:25
@tupe12334 
why does yarn is not supported? what causes it to fail when using yarn?

**Comment by tupe12334** [comment] 2022-03-10 08:29
@yuval-hazaz @0xsapphir3 help me a lot to reproduce this problem because it does not happen to me because I use npm.
I didn't start to go deeper because I'm focusing on #2374 , @0xsapphir3 said that he want to dig deeper and he will let me know if he found anything

**Comment by yuval-hazaz** [comment] 2022-05-15 07:57
@tupe12334 is that something we need to add to the docs as troubleshooting? 
Is there anything else to do with this issue or should we close it?

**Closed** 2022-08-28 12:15 UTC
Labels: type: bug, generated server, status: assigned
