### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rabebb** [amplication/amplication#3993] opened 2022-09-30 08:32 UTC
### Feature description

add customized error messages to base api. like http exception filter but more specific. for example, in create a user when there's a duplicate unique element, it returns "500 internal server error" and in the terminal it returns "unique constraint failed on the  field x". so instead i will be able to display the specific error without having to create a custom api.

thank you

**Comment by souravjain540** [comment] 2022-10-01 15:21
Thanks for your suggestion. 

@yuval-hazaz @arielweinberger your thoughts?

**Comment by alhaxkar** [comment] 2022-10-03 22:45
@souravjain540  I'm looking forward to helping the community, Could I take a look on it?

**Comment by yuval-hazaz** [comment] 2022-10-08 17:06
Thanks for you suggestion, we will look at this soon

**Comment by Ruchika30** [comment] 2022-10-15 11:48
I can look into it . Can this be assigned to me ? @yuval-hazaz @souravjain540

**Comment by yuval-hazaz** [comment] 2022-10-15 13:43
This is a duplicate of https://github.com/amplication/amplication/issues/2814 
There is already a PR in progress https://github.com/amplication/amplication/pull/3536

**Closed by yuval-hazaz** 2022-10-15 13:43 UTC
Labels: type: feature request
