### ISSUE TITLE
🐛 Bug Report: The contact us bot get's crash and very slow to load sometimes

### ISSUE THREAD

**Issue by Chirag8023** [amplication/amplication#5793] opened 2023-04-13 22:13 UTC
### What happened?

The "contact us" service is really slow to load and sometimes when tried to open multiple times, it get crashed and didn't open

![Screenshot (22)](https://user-images.githubusercontent.com/84070677/231892377-67a39ef1-0cfd-4679-abd4-c4a42c2bb6e2.png)
![Screenshot (24)](https://user-images.githubusercontent.com/84070677/231891525-671890f9-1b81-4549-b5b6-bd1acfa9ab7f.png)

### What you expected to happen

when open contact it loads fastly and also answer fastly to the questions, and didn't get crash if we tried to open it multiple times

### How to reproduce

Click on the Help button in the right side of the navbar, then click on the "Contact Us", We can see that it's really slow in loading.
If we continue this process for X times we will see that the transparent box for "Contact Us" will appear but nothing will happen after that. IF DON'T HAPPEN THEN RELOAD THE PAGE & TRY AGAIN.

### Amplication version

1.5.0

### Environment

Online app : app.amplication.com

**Comment by GreenMachine01** [comment] 2023-04-24 11:17
seems like a duplicate of - https://github.com/amplication/amplication/issues/5047

**Closed by GreenMachine01** 2023-04-24 11:17 UTC
Labels: type: bug
