### ISSUE TITLE
As Dev - I want CI for Plugin repository

### ISSUE THREAD

**Issue by EugeneTseitlin** [amplication/amplication#5130] opened 2023-02-06 14:20 UTC
### Feature description

Currently there is not automation in the plugins repo.
This causes broken tests not been found on time and linting not being aligned across the plugins.

We should run on any PR, at least lint, test and build each plugin affected.

**Comment by overbit** [comment] 2023-10-30 10:51
@mulygottlieb this is the first issue we spoke about last week

**Comment by mulygottlieb** [comment] 2023-11-27 10:35
@abrl91 @overbit - Can this go into "Done"? Or be closed as a duplicate of other tickets you already worked on last week?
Please update the ticket status.

**Comment by abrl91** [comment] 2023-11-27 11:20
https://github.com/amplication/amplication/issues/7441

**Closed by abrl91** 2023-11-27 11:20 UTC
Labels: type: devops, type:plugin, epic: Plugins, impact: Productivity
