### ISSUE TITLE
Docs: Add a description of JSON data type

### ISSUE THREAD

**Issue by MoFoGo** [amplication/amplication#2875] opened 2022-06-06 16:32 UTC
### Describe the issue with documentation

The docs are missing a  description of JSON data type

### How to solve the problem

Update the [Creating a New Entity Field](https://docs.amplication.com/docs/how-to/create-entity-field/) article to include more info about JSON

**Comment by MoFoGo** [comment] 2022-06-06 16:34
Relates to PR:

Update-entity-fields #154

**Comment by souravjain540** [comment] 2022-08-17 08:39
@veera6513 sure!

Join our discord for any support in making PR to solving the issue

**Comment by souravjain540** [comment] 2022-08-20 15:33
@veera6513 any updates?

**Comment by veera6513** [comment] 2022-08-20 15:42
Actually I had some personal work...I will try complete by tomorrow.

**Comment by souravjain540** [comment] 2022-08-23 09:24
@veera6513 are you working on this?

If not, can I assign it to someone else?

**Comment by ParkourKarthik** [comment] 2022-08-25 07:47
I would like to pick this up.

**Comment by souravjain540** [comment] 2022-08-25 07:50
> I would like to pick this up.

Only first time contributors can participate in this :)

**Comment by Abhay5855** [comment] 2022-09-11 06:49
I can take this issue can you assign it to me

**Comment by souravjain540** [comment] 2022-09-11 06:58
> I can take this issue can you assign it to me

Sure

**Comment by Abhay5855** [comment] 2022-09-11 09:43
cloned the repo and started working on it thank you

**Comment by prakhar-198** [comment] 2022-10-12 06:16
Hey! if the issue is still not fixed..Please can you assign me..I'll fix it! @souravjain540

**Comment by yuval-hazaz** [comment] 2022-10-15 07:02
@Abhay5855 please let us know if you need any help with that

**Comment by Abhay5855** [comment] 2022-10-15 08:06
@yuval-hazaz  yes sure

**Closed** 2023-04-19 08:39 UTC
Labels: type: bug, type: docs, good first issue, open to community
