### ISSUE TITLE
As a User - I don't want to see any  @ts-ignore and eslint-disable in my generated code

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6703] opened 2023-08-20 11:49 UTC
The code generated by amplication contains few @ts-ignore and eslint-disable comments that, for a typescript, production ready code, it must not happen.

i.e. 
```ts
// main.ts 

import { ValidationPipe } from "@nestjs/common";
import { HttpAdapterHost, NestFactory } from "@nestjs/core";
import { OpenAPIObject, SwaggerModule } from "@nestjs/swagger";
import { HttpExceptionFilter } from "./filters/HttpExceptions.filter";
// @ts-ignore
// eslint-disable-next-line
import { AppModule } from "./app.module";
import {
  swaggerPath,
  swaggerDocumentOptions,
  swaggerSetupOptions,
  // @ts-ignore
  // eslint-disable-next-line
} from "./swagger";

const { PORT = 3000 } = process.env;

async function main() {
  const app = await NestFactory.create(AppModule, { cors: true });

  app.setGlobalPrefix("api");
  app.useGlobalPipes(
    new ValidationPipe({
      transform: true,
      forbidUnknownValues: false,
    })
  );

```

**Comment by PazYanoverr** [comment] 2023-12-31 13:57
Closed as duplicate of #7668

**Closed by PazYanoverr** 2023-12-31 13:57 UTC
