### ISSUE TITLE
As PO - I want a message in the build log when the app generation finished successfully

### ISSUE THREAD

**Issue by mulygottlieb** [amplication/amplication#6296] opened 2023-06-18 11:27 UTC
### Feature description

Today, if you generate code without being connected to a git provider, you will not get the `Successfully pushed changes to Github` message, and your last message on the build log would be `Formatting code...`

We want, when the code generation finished (and the green checkmark is marked next to 
![image](https://github.com/amplication/amplication/assets/1912933/0b065989-45de-482a-9da1-32ab2cc8c464)

To also add a line to the build log saying:
`Successfully Generated Application`

### Use case

Clearer build log when no git provider is used

**Comment by kirtanchandak** [comment] 2023-06-29 21:36
Can I work on this issue?

**Comment by ashutosh887** [comment] 2023-07-14 15:01
@souravjain540 let me work on this

**Comment by jeffmchang** [comment] 2023-07-19 23:48
## Proposal

### Please re-state the problem that we are trying to solve in this issue.

- The current issue is that the panel for the 'Generate Code' is not properly displaying the correct status:

![image](https://github.com/amplication/amplication/assets/109321774/c5faaffb-bc7a-4d2c-b9e0-a7105a2c3d81)


### What is the root cause of that problem?

- The root cause of the problem seems to be coming from BuildSteps.tsx on line 27:

![image](https://github.com/amplication/amplication/assets/109321774/8c30a09e-6a76-4a1f-89dd-dece6cc3de17)


- The `data.build.action.steps.find((step) => step.name === GENERATE_STEP_NAME)` is calling for a `step.name` that is `GENERATE_APPLICATION`

![image](https://github.com/amplication/amplication/assets/109321774/8b6e87d8-5ae6-4877-9618-42f649f4aa20)


- But upon successful completion, the object returns`ADD_TO_QUEUE`:

![image](https://github.com/amplication/amplication/assets/109321774/20c1354f-6448-4010-bc32-61f9869036b9)



### What changes do you think we should make in order to solve the problem?

- Changing `GENERATE_STEP_NAME` to `ADD_TO_QUEUE` leads to the expected result:

![image](https://github.com/amplication/amplication/assets/109321774/e1964c5c-7fd1-4d9d-bbca-2a27f782dd0b)
![image](https://github.com/amplication/amplication/assets/109321774/eb14816a-30fe-4856-b31f-b11de54a7e25)

**Comment by professorabhay** [comment] 2023-09-27 14:20
Hey @souravjain540, If that issue is still not resolved then please assign it to me. I would like to contribute!

**Comment by souravjain540** [comment] 2023-10-03 05:55
@jeffmchang do you want to work on this issue?

**Comment by mulygottlieb** [comment] 2023-10-03 07:28
@souravjain540 I am sorry for the confusion, this one seems to be already solved


![Image](https://github.com/amplication/amplication/assets/1912933/c95267fa-846a-46c8-85ec-1e96a4ae8b54)

**Closed** 2023-10-09 05:43 UTC
Labels: good first issue, type: feature request, open to community
